export type TailwindColor =
    | "brand"
    | "orange"
    | "violet"
    | "red"
    | "amber"
    | "yellow"
    | "lime"
    | "green"
    | "emerald"
    | "teal"
    | "cyan"
    | "blue"
    | "indigo"
    | "purple"
    | "fushia"
    | "pink"
    | "rose";
